version: '3.8'

services:
  db:
    container_name: cheems_db
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_ROOT_LOCALHOST: ${DATABASE_HOST}
      MYSQL_ROOT_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: