import { Knex } from 'knex'

/* eslint max-len: 0 */
export async function seed (knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('producers').del()

  // Inserts seed entries
  await knex('producers').insert([
    { id: '2d57216d-1a91-4ee7-b4a5-ac56cf89d018', name: 'Apaches entertainment SL', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', brand_hex_color: '#B8D235', image_url: 'https://fotografias.atresmediacorporacion.com/clipping/cmsimages02/2017/02/13/0322A405-A1A1-4EE3-9D56-F05B0682B63A/58.jpg' },
    { id: 'ad57216d-1a91-4ee7-b4a5-ac56cf89d017', name: 'Atresmedia cina SL', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', brand_hex_color: '#D23559', image_url: 'https://album.mediaset.es/file/10002/2017/11/17/telecinco_circular_500_-1_bda1.png' },
    { id: '3d57216d-1a91-4ee7-b4a5-ac56cf89d016', name: 'Telecinco cinema SAU', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', brand_hex_color: '#439839', image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Marvel_Studios_logo.svg/2560px-Marvel_Studios_logo.svg.png', parent_producer_id: 'ad57216d-1a91-4ee7-b4a5-ac56cf89d017' },
    { id: '5d57216d-1a91-4ee7-b4a5-ac56cf89d015', name: 'Walt Disney Studios', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', brand_hex_color: '#3574D2', image_url: 'https://graffica.info/wp-content/uploads/2018/07/Logo_de_Walt_Disney_Pictures.jpg' },
    { id: '1d27216d-1a91-4ee7-b4a5-ac56cf89d014', name: 'Marvel Studios', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', brand_hex_color: '#983939', image_url: 'https://i0.wp.com/www.tomosygrapas.com/wp-content/uploads/2016/07/marvelstudios-7611c.jpg', parent_producer_id: '5d57216d-1a91-4ee7-b4a5-ac56cf89d015' },
    { id: '4d57216d-1a91-4ee7-b4a5-ac56cf89d013', name: 'Warner Bros. Entertainment', description: '', brand_hex_color: '#6F4F56', image_url: 'https://brandemia.org/sites/default/files/inline/images/wb_logo_portada.jpg' },
    { id: '257216d1-1a91-4ee7-b4a5-ac56cf89d012', name: 'NBCUniversal', description: '', brand_hex_color: '#813F23', image_url: null },
    { id: '1e57216d-1a91-4ee7-b4a5-ac56cf89d011', name: 'Sony Pictures', description: '', brand_hex_color: '#FF4D00', image_url: null },
    { id: '7e57216d-1a91-4ee7-b4a5-ac56cf89d010', name: 'Paramount Global', description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', brand_hex_color: '#FF4D00', image_url: null },
  ])
}
