import { Knex } from 'knex'

/* eslint max-len: 0 */
export async function seed (knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('translations').del()

  // Inserts seed entries
  await knex('translations').insert([
    { translatable_id: '1d57216d-1a91-4ee7-b4a5-ac56cf89d010', translatable_type: 'Post', field: 'title', value: 'Evite los 10 principales errores cometidos al comenzar TUBE VIDEO', language: 'es' },
    { translatable_id: '1d57216d-1a91-4ee7-b4a5-ac56cf89d010', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: 'bd57216d-1a91-4ee7-b4a5-ac56cf89d011', translatable_type: 'Post', field: 'title', value: 'Creer estos 5 mitos sobre las pruebas te impide crecer', language: 'es' },
    { translatable_id: 'bd57216d-1a91-4ee7-b4a5-ac56cf89d011', translatable_type: 'Post', field: 'description', value: 'Mi familia no es muy grande, somos solo cuatro personas: mi padre, mi madre, mi hermana y yo. También tenemos un perro.\\n\\nYo soy mayor que mi hermana, pero ella es más alta. Yo tengo doce años y ella once. Mis padres se llaman Javier y María, mi hermana se llama Sara y yo Luis. Vivimos todos juntos en una casa muy bonita.\\n\\nMi padre es banquero y mi madre ama de casa. Por la mañana, desayunamos juntos en la cocina. Me gusta desayunar con mi familia. Además, por las mañanas siempre tengo hambre. Después del colegio, mi madre prepara una comida deliciosa. Por la tarde, mi madre queda con sus amigas, y mi padre juega al tenis. Mi hermana y yo hacemos los deberes, y después vemos la televisión. Los viernes por la tarde vamos los cuatro de compras.\\n\\nMi padre es alto y rubio, y mi madre es morena y delgada. A mi hermana le gusta quedar con sus amigas en el parque. Yo me divierto mucho más jugando a los videojuegos en casa.', language: 'es' },
    { translatable_id: 'cd57216d-1a91-4ee7-b4a5-ac56cf89d012', translatable_type: 'Post', field: 'title', value: '¡No pierdas el tiempo! 5 hechos hasta que llegues a tu prueba', language: 'es' },
    { translatable_id: 'dd57216d-1a91-4ee7-b4a5-ac56cf89d013', translatable_type: 'Post', field: 'title', value: 'PRUEBAS SIN ESFUERZO GARANTIZADAS', language: 'es' },
    { translatable_id: 'dd57216d-1a91-4ee7-b4a5-ac56cf89d013', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: 'fd57216d-1a91-4ee7-b4a5-ac56cf89d015', translatable_type: 'Post', field: 'title', value: 'Lo que debería haber preguntado a sus maestros sobre las pruebas', language: 'es' },
    { translatable_id: 'fd57216d-1a91-4ee7-b4a5-ac56cf89d015', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: 'd57216d1-1a91-4ee7-b4a5-ac56cf89d016', translatable_type: 'Post', field: 'title', value: 'Secretos para realizar PRUEBAS, incluso en esta economía en recesión', language: 'es' },
    { translatable_id: 'd57216d1-1a91-4ee7-b4a5-ac56cf89d016', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: 'ad57216d-1a91-4ee7-b4a5-ac56cf89d017', translatable_type: 'Post', field: 'title', value: 'Enamórate de las PRUEBAS', language: 'es' },
    { translatable_id: 'ad57216d-1a91-4ee7-b4a5-ac56cf89d017', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: '3d57216d-1a91-4ee7-b4a5-ac56cf89d018', translatable_type: 'Post', field: 'title', value: 'Conocer estos 8 secretos hará que sus pruebas se vean increíbles', language: 'es' },
    { translatable_id: '3d57216d-1a91-4ee7-b4a5-ac56cf89d018', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: '2d57216d-1a91-4ee7-b4a5-ac56cf89d019', translatable_type: 'Post', field: 'title', value: 'Pruebas con un presupuesto ajustado: 8 consejos de la Gran Depresión', language: 'es' },
    { translatable_id: '2d57216d-1a91-4ee7-b4a5-ac56cf89d019', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: '4d57216d-1a91-4ee7-b4a5-ac56cf89d020', translatable_type: 'Post', field: 'title', value: 'Master The Art Of Testing With These 8 Tips', language: 'es' },
    { translatable_id: '4d57216d-1a91-4ee7-b4a5-ac56cf89d020', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
    { translatable_id: '5d57216d-1a91-4ee7-b4a5-ac56cf89d021', translatable_type: 'Post', field: 'title', value: 'Testing Awards: 8 Reasons Why They Don\'t Work & What You Can Do About It', language: 'es' },
    { translatable_id: '5d57216d-1a91-4ee7-b4a5-ac56cf89d021', translatable_type: 'Post', field: 'description', value: 'Lorem Ipsum es simplemente un texto ficticio de la industria de la impresión y la composición tipográfica. Lorem Ipsum ha sido el texto ficticio estándar de la industria desde el año 1500, cuando un impresor desconocido tomó una galera de tipos y la codificó para hacer un libro de muestras tipográficas. Ha sobrevivido no solo cinco siglos, sino también el salto a la composición tipográfica electrónica, permaneciendo esencialmente sin cambios. Se popularizó en la década de 1960 con el lanzamiento de hojas de Letraset que contenían pasajes de Lorem Ipsum y, más recientemente, con software de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.', language: 'es' },
  ])
}
