export const PRODUCER_VALIDATION = 'producer-validation-exception'
export const PRODUCER_SERVER_ERROR = 'producer-server-error'
export const PRODUCER_METHOD = 'producer-method-not-allowed'
export const PRODUCER_BAD_REQUEST = 'producer-bad-request'
export const PRODUCER_INVALID_SORTING_CRITERIA = 'producer-unprocessable-entity-invalid-sorting-criteria'
export const PRODUCER_INVALID_SORTING_OPTION = 'producer-unprocessable-entity-invalid-sorting-option'
export const PRODUCER_INVALID_PER_PAGE = 'producer-unprocessable-entity-invalid-per-page'
export const PRODUCER_INVALID_PAGE = 'producer-unprocessable-entity-invalid-page'
