/** Posts **/
export const POST_VALIDATION = 'post-validation-exception'
export const POST_SERVER_ERROR = 'post-server-error'
export const POST_METHOD = 'post-method-not-allowed'
export const POST_REACTION_ALREADY_EXISTS = 'post-conflict-user-already-exists'
export const POST_INVALID_SORTING_CRITERIA = 'post-unprocessable-entity-invalid-sorting-criteria'
export const POST_INVALID_SORTING_OPTION = 'post-unprocessable-entity-invalid-sorting-option'
export const POST_INVALID_FILTER_TYPE = 'post-unprocessable-entity-invalid-filter-type'
export const POST_INVALID_FILTER_VALUE = 'post-unprocessable-entity-invalid-filter-value'
export const POST_INVALID_PER_PAGE = 'post-unprocessable-entity-invalid-per-page'
export const POST_INVALID_PAGE = 'post-unprocessable-entity-invalid-page'
export const POST_POST_NOT_FOUND = 'post-post-not-found'
export const POST_BAD_REQUEST = 'post-bad-request'

/** Posts Comments **/
export const POST_COMMENT_AUTH_REQUIRED = 'post-comment-authentication-required'
export const POST_COMMENT_VALIDATION = 'post-comment-validation-exception'
export const POST_COMMENT_SERVER_ERROR = 'post-comment-server-error'
export const POST_COMMENT_CANNOT_DELETE_COMMENT = 'post-comment-conflict-cannot-delete-comment'
export const POST_COMMENT_CANNOT_UPDATE_COMMENT = 'post-comment-conflict-cannot-update-comment'
export const POST_COMMENT_BAD_REQUEST = 'post-comment-bad-request'
export const POST_COMMENT_FORBIDDEN = 'post-comment-forbidden'
export const POST_COMMENT_METHOD = 'post-comment-method-not-allowed'
export const POST_COMMENT_POST_NOT_FOUND = 'post-comment-post-not-found'
export const POST_COMMENT_COMMENT_NOT_FOUND = 'post-comment-post-comment-not-found'
export const POST_COMMENT_INVALID_PAGE = 'post-comment-unprocessable-entity-invalid-page'
export const POST_COMMENT_INVALID_PER_PAGE = 'post-comment-unprocessable-entity-invalid-per-page'

/** Post Child Comments **/
export const POST_CHILD_COMMENT_INVALID_PAGE = 'post-child-comment-unprocessable-entity-invalid-page'
export const POST_CHILD_COMMENT_INVALID_PER_PAGE = 'post-child-comment-unprocessable-entity-invalid-per-page'
export const POST_CHILD_COMMENT_BAD_REQUEST = 'post-child-comment-bad-request'
export const POST_CHILD_COMMENT_METHOD = 'post-child-comment-method-not-allowed'
export const POST_CHILD_COMMENT_VALIDATION = 'post-child-comment-validation-exception'
export const POST_CHILD_COMMENT_SERVER_ERROR = 'post-child-comment-server-error'
export const POST_CHILD_COMMENT_POST_NOT_FOUND = 'post-child-comment-post-not-found'
export const POST_CHILD_COMMENT_POST_COMMENT_NOT_FOUND = 'post-child-comment-post-comment-not-found'
export const POST_CHILD_COMMENT_PARENT_COMMENT_NOT_FOUND = 'post-child-comment-parent-comment-not-found'
export const POST_CHILD_COMMENT_AUTH_REQUIRED = 'post-child-comment-authentication-required'
export const POST_CHILD_COMMENT_FORBIDDEN = 'post-child-comment-forbidden-resource'
export const POST_CHILD_COMMENT_CANNOT_DELETE_CHILD_COMMENT = 'post-child-comment-cannot-delete-child-comment'
